# Generated by Django 4.0 on 2022-01-10 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studioapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='event_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
