# Generated by Django 4.0 on 2022-01-10 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studioapp', '0002_alter_events_event_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='event_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
