# Generated by Django 4.0 on 2022-01-10 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studioapp', '0003_alter_events_event_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='event_time',
            field=models.TimeField(max_length=20, null=True),
        ),
    ]
