# Generated by Django 4.0 on 2022-01-10 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studioapp', '0004_alter_events_event_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='event_date',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='events',
            name='event_time',
            field=models.TimeField(null=True),
        ),
    ]
