# Generated by Django 4.0 on 2022-01-15 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studioapp', '0006_alter_events_event_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='album_art',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
    ]
