# Generated by Django 4.0 on 2022-01-16 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studioapp', '0007_alter_song_album_art'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='album_art',
            field=models.ImageField(blank=True, null=True, upload_to='album_arts/'),
        ),
    ]
