# Generated by Django 4.0 on 2022-01-18 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studioapp', '0008_alter_song_album_art'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(default='John Doe', max_length=250, null=True)),
                ('mobile_number', models.CharField(default='0712345678', max_length=40, null=True)),
                ('email_address', models.EmailField(max_length=254, null=True)),
                ('facebook_link', models.CharField(blank=True, max_length=500, null=True)),
                ('instagram_link', models.CharField(blank=True, max_length=500, null=True)),
                ('youtube_link', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
