# Generated by Django 4.0 on 2022-01-18 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studioapp', '0009_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='booking_date',
            field=models.DateTimeField(null=True),
        ),
    ]
