# Generated by Django 4.0 on 2022-01-18 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studioapp', '0011_session_booking_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='booking_time',
            field=models.TimeField(null=True),
        ),
    ]
