# Generated by Django 4.0 on 2022-01-18 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studioapp', '0013_alter_session_booking_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='booking_time',
        ),
    ]
