# Generated by Django 4.0 on 2022-01-18 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studioapp', '0015_alter_session_booking_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='booking_time',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='booking_date',
            field=models.DateField(null=True),
        ),
    ]
